/*

 BANGMAP01.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : bangtiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bangmap01Width 32
#define bangmap01Height 18
#define bangmap01Bank 0

extern unsigned char bangmap01[];

/* End of BANGMAP01.H */
